---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    when:
      label: "breaking-change"
  - title: "✨ New features"
    when:
      label: "new-feature"
  - title: "🐛 Bug fixes"
    when:
      label: "bugfix"
  - title: "🚀 Enhancements"
    when:
      labels:
        - "enhancement"
        - "refactor"
        - "performance"
  - title: "🧰 Maintenance"
    when:
      labels:
        - "maintenance"
        - "ci"
  - title: "📚 Documentation"
    when:
      label: "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    when:
      label: "dependencies"
  - type: "pre-exclude"
    when:
      label: "sync"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - "major"
        - "breaking-change"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - "minor"
        - "new-feature"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - "bugfix"
        - "chore"
        - "ci"
        - "dependencies"
        - "documentation"
        - "enhancement"
        - "performance"
        - "refactor"
  - type: "version-resolver"
    semver-increment: "patch"

template: |
  ## What's changed

  _To receive a notification on new releases, click on **Watch** > **Custom** > **Releases** on the top._

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
