preserve_hierarchy: 1
files:
  - source: /lang/en/*.json
    ignore:
      - /lang/en/dashboard.json
      - /lang/en/legal.json
    translation: /lang/%locale%/%original_file_name%
    update_option: update_as_unapproved
