export const SCENE_3D_THEME = {
  dark: {
    bg: "#2e4870" as `#${string}`,
    fog: "#2e4870" as `#${string}`,
    ambientIntensity: 0.55,
    dirIntensity: 1.6,
    dirColor: "#fff4e6" as `#${string}`,
    terrainColor: "#080e15" as `#${string}`,
    groundColor: "#142234" as `#${string}`,
    groundChecker: "#192b40" as `#${string}`,
    groundBorder: "#2b435a" as `#${string}`,
    gridCell: "#425a70" as `#${string}`,
    gridSection: "#6f8498" as `#${string}`,
    gridCellThickness: 0.45,
    gridSectionThickness: 0.9,
    routeSelectedColor: "#93c5fd" as `#${string}`,
    routeSelectedEmissive: "#60a5fa" as `#${string}`,
    routeSelectedEmissiveIntensity: 0.8,
    skyTop: "#182848" as `#${string}`,
    skyHorizon: "#2e4870" as `#${string}`,
    hemisphereSky: "#203858" as `#${string}`,
    hemisphereGround: "#080e0a" as `#${string}`,
    hemisphereIntensity: 0.3,
  },
  light: {
    bg: "#e4f0fa" as `#${string}`,
    fog: "#e4f0fa" as `#${string}`,
    ambientIntensity: 1.0,
    dirIntensity: 2.0,
    dirColor: "#fffaf5" as `#${string}`,
    terrainColor: "#b7c4cf" as `#${string}`,
    groundColor: "#d0d8e4" as `#${string}`,
    groundChecker: "#c2ccd7" as `#${string}`,
    groundBorder: "#8da3b8" as `#${string}`,
    gridCell: "#7890a6" as `#${string}`,
    gridSection: "#526f8b" as `#${string}`,
    gridCellThickness: 0.75,
    gridSectionThickness: 1.15,
    routeSelectedColor: "#1d4ed8" as `#${string}`,
    routeSelectedEmissive: "#1e40af" as `#${string}`,
    routeSelectedEmissiveIntensity: 0.15,
    skyTop: "#68a8de" as `#${string}`,
    skyHorizon: "#e4f0fa" as `#${string}`,
    hemisphereSky: "#90c0e8" as `#${string}`,
    hemisphereGround: "#b0a070" as `#${string}`,
    hemisphereIntensity: 0.2,
  },
} as const;

export type Scene3DTheme = (typeof SCENE_3D_THEME)[keyof typeof SCENE_3D_THEME];
