---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Label Syncer
        uses: srealmoreno/label-sync-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: https://raw.githubusercontent.com/dutchdronesquad/.github/main/.github/labels.yml
